export { AddMovie } from './AddMovie';
export { EditMovie } from './EditMovie';
export { NotFound } from './NotFound';
export { Home } from './Home';
export { Search } from './Search';
export { Detail } from './Detail';
export { AllMovies } from './AllMovies';
export { AllReleases } from './AllReleases';
export { Stats } from './Stats';
